### ISSUE TITLE
USER STORY: Register an account

### ISSUE THREAD

**Issue by davidb3rgqvist** [davidb3rgqvist/project4#2]
### User Story

As a **user**, I can **register an account on the recipe webpage** so that **I can save my favorite recipes and interact with the community.**

### Acceptance Criteria

1. **Registration Form:**
   - User should be presented with a registration form requesting username and password.

2. **Confirmation:**
   - Upon successful registration, a message should be displayed prompting it was successful.

3. **Validation:**
   - If the user tries to register with an username that is already in use, an error message should be displayed prompting them to choose a different name.

### Tasks
- [x] Implement a registration form with fields for username and password.
- [x] Display success message upon successful registration.
- [x] Display error message upon error in the registration form.
